services:
    # Custom Annotation Loader
    ronte_ltd_json_api.mapping.annotation_loader:
        class: RonteLtd\JsonApiBundle\Serializer\Mapping\Loader\AnnotationLoader
        arguments: ["@annotations.reader"]
        public: false

    # Custom Metadata Factory
    ronte_ltd_json_api.mapping.metadata_factory:
        class: RonteLtd\JsonApiBundle\Serializer\Mapping\Factory\MetadataFactory
        arguments: ["@ronte_ltd_json_api.mapping.annotation_loader"]
        public: false

    # Custom Metadata Factory TODO implement cache factory
#    ronte_ltd_json_api.mapping.cache_class_metadata_factory:
#        class: Symfony\Component\Serializer\Mapping\Factory\CacheClassMetadataFactory
#        arguments: ["@ronte_ltd_json_api.mapping.class_metadata_factory"]
#        public: false

    # Json Api Normalizer
    ronte_ltd_json_api.normalizer.object_normalizer:
        class: RonteLtd\JsonApiBundle\Serializer\Normalizer\ObjectNormalizer
        arguments:
            - "@ronte_ltd_json_api.mapping.metadata_factory"
            - "@serializer.mapping.class_metadata_factory"
            - "@serializer.name_converter.camel_case_to_snake_case"
        public: false
        autowire: true
        tags:
            - { name: "serializer.normalizer", priority: 2 }

    # Json Api Normalizer
    ronte_ltd_json_api.normalizer.data_collection_normalizer:
        class: RonteLtd\JsonApiBundle\Serializer\Normalizer\DataCollectionNormalizer
        arguments:
            - "@ronte_ltd_json_api.mapping.metadata_factory"
            - "@serializer.mapping.class_metadata_factory"
            - "@serializer.name_converter.camel_case_to_snake_case"
        public: false
        autowire: true
        tags:
            - { name: "serializer.normalizer", priority: 1 }