services:
    # Json Api Normalizer
    ronte_ltd_json_api.normalizer.jsonapi:
        class: RonteLtd\JsonApiBundle\Serializer\Normalizer\JsonApiNormalizer
        public: false
        autowire: true
        tags:
            - { name: serializer.normalizer }